<?php
declare(strict_types=1);

namespace VpMail;

/**
 * Email catalogue — every message VerifyPass needs
 * (docs/EMAIL_REQUIREMENTS.md). Variables are {var} placeholders, escaped by
 * the Renderer. requiredVars are enforced by send.php.
 *
 * Action URLs (verify/reset/invite) are generated by the Node backend — it
 * owns users, sessions and tokens — and passed in as vars.actionUrl.
 */
final class Templates
{
    public const CATALOG = [
        // Account lifecycle
        'verify_email' => [
            'subject' => 'Confirm your VerifyPass workspace email',
            'preheader' => 'One click confirms this address secures your workspace.',
            'paragraphs' => [
                'Confirm this email address to secure the {companyName} workspace on VerifyPass.',
                'This link expires in 24 hours. If you did not create this account, ignore this message.',
            ],
            'facts' => [],
            'cta' => ['label' => 'Confirm email', 'var' => 'actionUrl'],
            'required' => ['companyName', 'actionUrl'],
        ],
        'welcome' => [
            'subject' => 'Welcome to VerifyPass — your sandbox is ready',
            'preheader' => 'Three steps to your first test verification.',
            'paragraphs' => [
                'Your {companyName} workspace is ready in sandbox mode. Sandbox uses test keys and never touches live traffic.',
                'Next: finish your business profile, create test API keys, then run one test verification.',
            ],
            'facts' => [],
            'cta' => ['label' => 'Finish setup', 'var' => 'dashboardUrl'],
            'required' => ['companyName'],
        ],
        'team_invite' => [
            'subject' => 'You\'ve been added to the {companyName} workspace on VerifyPass',
            'preheader' => '{inviter} invited you as {role}.',
            'paragraphs' => [
                '{inviter} added you to the {companyName} workspace with the role {role}.',
                'Set your own password to activate access. This link works once and expires in 72 hours.',
                'If you were not expecting this invitation, ignore it — the link will expire unused.',
            ],
            'facts' => [['Workspace', 'companyName'], ['Role', 'role'], ['Invited by', 'inviter']],
            'cta' => ['label' => 'Set your password', 'var' => 'actionUrl'],
            'required' => ['companyName', 'role', 'inviter', 'actionUrl'],
        ],
        'password_reset' => [
            'subject' => 'Reset your VerifyPass password',
            'preheader' => 'A reset was requested for your account.',
            'paragraphs' => [
                'A password reset was requested for your VerifyPass account.',
                'This link works once and expires in 30 minutes. If you did not request it, ignore this message — your password stays unchanged.',
            ],
            'facts' => [['Requested at (UTC)', 'requestedAt'], ['IP address', 'ip']],
            'cta' => ['label' => 'Choose a new password', 'var' => 'actionUrl'],
            'required' => ['requestedAt', 'ip', 'actionUrl'],
        ],
        'password_changed' => [
            'subject' => 'Your VerifyPass password was changed',
            'preheader' => 'If this was not you, act now.',
            'paragraphs' => [
                'The password on your VerifyPass account was changed.',
                'If you did not do this, reset your password immediately and contact support.',
            ],
            'facts' => [['Changed at (UTC)', 'changedAt'], ['IP address', 'ip']],
            'cta' => ['label' => 'Secure my account', 'var' => 'securityUrl'],
            'required' => ['changedAt', 'ip'],
        ],
        'email_change_notice' => [
            'subject' => 'Email change requested for your VerifyPass account',
            'preheader' => 'Sent to your current address on file.',
            'paragraphs' => [
                'A request was made to change the sign-in email on your account to {newEmailMasked}.',
                'Nothing changes until the new address confirms. If this was not you, cancel the request now.',
            ],
            'facts' => [['New address', 'newEmailMasked'], ['Requested at (UTC)', 'requestedAt']],
            'cta' => ['label' => 'Cancel this change', 'var' => 'actionUrl'],
            'required' => ['newEmailMasked', 'requestedAt', 'actionUrl'],
        ],
        'mfa_changed' => [
            'subject' => 'Two-factor authentication changed on your VerifyPass account',
            'preheader' => 'Security settings on your account changed.',
            'paragraphs' => [
                'Two-factor authentication was {changeKind} on your VerifyPass account.',
                'If you did not make this change, reset your password and contact support immediately.',
            ],
            'facts' => [['Change', 'changeKind'], ['When (UTC)', 'changedAt'], ['IP address', 'ip']],
            'cta' => ['label' => 'Review account security', 'var' => 'securityUrl'],
            'required' => ['changeKind', 'changedAt', 'ip'],
        ],
        'new_signin' => [
            'subject' => 'New sign-in to your VerifyPass account',
            'preheader' => 'A new device or location signed in.',
            'paragraphs' => [
                'Your account was signed in from a device or location we have not seen before.',
                'If this was you, no action is needed. If not, secure your account now.',
            ],
            'facts' => [['When (UTC)', 'signedInAt'], ['IP address', 'ip'], ['Device', 'device']],
            'cta' => ['label' => 'Secure my account', 'var' => 'securityUrl'],
            'required' => ['signedInAt', 'ip', 'device'],
        ],

        // Operational (tenant)
        'api_key_event' => [
            'subject' => 'API key {keyAction} for {companyName} ({environment})',
            'preheader' => 'Credential change on your workspace.',
            'paragraphs' => [
                'An API key was {keyAction} for the {companyName} workspace ({environment} environment).',
                'If you did not do this, revoke the key and review account access immediately.',
            ],
            'facts' => [['Key prefix', 'keyPrefix'], ['Action', 'keyAction'], ['Actor', 'actor'], ['When (UTC)', 'changedAt']],
            'cta' => ['label' => 'Review API keys', 'var' => 'settingsUrl'],
            'required' => ['companyName', 'environment', 'keyAction', 'keyPrefix', 'actor', 'changedAt'],
        ],
        'webhook_changed' => [
            'subject' => 'Webhook settings changed for {companyName}',
            'preheader' => 'Verification result delivery settings changed.',
            'paragraphs' => [
                'Webhook settings for {companyName} were changed. New endpoint host: {endpointHost}. Signing secret rotated: {secretRotated}.',
                'If you did not make this change, rotate the signing secret and review API keys immediately.',
            ],
            'facts' => [['Endpoint host', 'endpointHost'], ['Secret rotated', 'secretRotated'], ['Actor', 'actor'], ['When (UTC)', 'changedAt']],
            'cta' => ['label' => 'Review webhooks', 'var' => 'webhooksUrl'],
            'required' => ['companyName', 'endpointHost', 'secretRotated', 'actor', 'changedAt'],
        ],
        'webhook_failing' => [
            'subject' => 'Action needed: verification results are not reaching your endpoint',
            'preheader' => 'Deliveries to your endpoint have been failing.',
            'paragraphs' => [
                'Verification result deliveries to {endpointHost} are failing ({errorClass}). Results are queued and none are lost.',
                'Fix the endpoint or switch to polling, then retry from the delivery log.',
            ],
            'facts' => [['Endpoint host', 'endpointHost'], ['Error', 'errorClass'], ['Attempts', 'attempts'], ['When (UTC)', 'failedAt']],
            'cta' => ['label' => 'Open delivery log', 'var' => 'webhooksUrl'],
            'required' => ['endpointHost', 'errorClass', 'attempts', 'failedAt'],
        ],
        'review_waiting' => [
            'subject' => 'Review needed: {pendingCount} verification case(s) waiting',
            'preheader' => 'Your review queue has cases waiting.',
            'paragraphs' => [
                '{pendingCount} verification case(s) are waiting for review in the {companyName} workspace. Oldest has waited {oldestWait}.',
                'No customer details are included in this email — sign in to review.',
            ],
            'facts' => [['Cases waiting', 'pendingCount'], ['Oldest wait', 'oldestWait']],
            'cta' => ['label' => 'Open review queue', 'var' => 'reviewUrl'],
            'required' => ['companyName', 'pendingCount', 'oldestWait'],
        ],
        'review_second_confirmation' => [
            'subject' => 'A review decision needs a second confirmation',
            'preheader' => 'Dual-approval policy: one more reviewer must confirm.',
            'paragraphs' => [
                '{proposer} proposed {proposedDecision} on a case in your workspace. Your dual-approval policy requires a second, different reviewer to confirm.',
            ],
            'facts' => [['Proposed by', 'proposer'], ['Proposed decision', 'proposedDecision'], ['Case age', 'caseAge']],
            'cta' => ['label' => 'Open review queue', 'var' => 'reviewUrl'],
            'required' => ['proposer', 'proposedDecision', 'caseAge'],
        ],
        'production_request_ops' => [
            'subject' => 'Production access request: {companyName}',
            'preheader' => 'A tenant requested production activation.',
            'paragraphs' => [
                '{companyName} (contact: {contactEmail}) requested production access.',
                'Onboarding checklist: {checklistSummary}. Review before enabling live keys.',
            ],
            'facts' => [['Tenant', 'tenantUid'], ['Contact', 'contactEmail'], ['Test sessions', 'testSessions']],
            'cta' => ['label' => 'Review request', 'var' => 'adminUrl'],
            'required' => ['companyName', 'tenantUid', 'contactEmail', 'checklistSummary', 'testSessions'],
        ],
        'production_decision' => [
            'subject' => 'Your VerifyPass production access request: {decision}',
            'preheader' => 'Decision on your production activation request.',
            'paragraphs' => [
                'Your request for production access was {decision}.',
                '{reasonText}',
            ],
            'facts' => [['Decision', 'decision'], ['Decided at (UTC)', 'decidedAt']],
            'cta' => ['label' => 'Open your workspace', 'var' => 'dashboardUrl'],
            'required' => ['decision', 'reasonText', 'decidedAt'],
        ],
        'workspace_status' => [
            'subject' => 'Your VerifyPass workspace has been {statusChange}',
            'preheader' => 'Workspace status change.',
            'paragraphs' => [
                'The {companyName} workspace was {statusChange}, effective {effectiveAt} (UTC). Reason category: {reasonCategory}.',
                'If you believe this is a mistake, reply to this email or contact support.',
            ],
            'facts' => [['Status', 'statusChange'], ['Effective (UTC)', 'effectiveAt'], ['Reason', 'reasonCategory']],
            'cta' => ['label' => 'Contact support', 'var' => 'supportUrl'],
            'required' => ['companyName', 'statusChange', 'effectiveAt', 'reasonCategory'],
        ],
        'evidence_purge_notice' => [
            'subject' => 'Evidence for {caseCount} completed cases will be deleted on {purgeDate}',
            'preheader' => 'Retention policy purge approaching.',
            'paragraphs' => [
                'Under your retention policy, stored evidence for {caseCount} completed verification case(s) will be permanently deleted on {purgeDate} (UTC).',
                'This cannot be undone. Export any case files you need before that date.',
            ],
            'facts' => [['Cases', 'caseCount'], ['Purge date (UTC)', 'purgeDate'], ['Policy', 'policySummary']],
            'cta' => ['label' => 'Export case files', 'var' => 'reportsUrl'],
            'required' => ['caseCount', 'purgeDate', 'policySummary'],
        ],

        // Compliance
        'deletion_completed' => [
            'subject' => 'Biometric data deletion completed (reference {auditRef})',
            'preheader' => 'A deletion request has been fulfilled.',
            'paragraphs' => [
                'The requested biometric data deletion completed at {completedAt} (UTC).',
                '{sessionsAffected} session(s) and {filesDeleted} file(s) were removed. Decision scores and audit metadata are retained per the published retention policy.',
            ],
            'facts' => [['Audit reference', 'auditRef'], ['Sessions affected', 'sessionsAffected'], ['Files deleted', 'filesDeleted'], ['Completed (UTC)', 'completedAt']],
            'cta' => ['label' => 'View audit log', 'var' => 'reportsUrl'],
            'required' => ['auditRef', 'sessionsAffected', 'filesDeleted', 'completedAt'],
        ],
        'incident_notice' => [
            'subject' => 'Important security notice for your VerifyPass workspace',
            'preheader' => 'A security incident may affect your workspace.',
            'paragraphs' => [
                'Between {windowStart} and {windowEnd} (UTC), a security incident may have involved the following categories of workspace data: {dataCategories}.',
                'Actions taken: {actionsTaken}',
                'What you should do: {tenantActions}',
                'We take this seriously. Contact our security team with any questions.',
            ],
            'facts' => [['Window start (UTC)', 'windowStart'], ['Reference', 'incidentRef']],
            'cta' => ['label' => 'Contact security team', 'var' => 'supportUrl'],
            'required' => ['windowStart', 'windowEnd', 'dataCategories', 'actionsTaken', 'tenantActions', 'incidentRef'],
        ],
        'weekly_digest' => [
            'subject' => 'Your VerifyPass week: {totalVerifications} verifications',
            'preheader' => 'Volume, outcomes and queue health for the week.',
            'paragraphs' => [
                'This week in {companyName}: {totalVerifications} verifications — {approvedCount} approved, {rejectedCount} rejected, {reviewCount} in review.',
                'Top rejection reasons: {topReasons}. Review queue depth: {queueDepth}. Webhook health: {webhookHealth}.',
            ],
            'facts' => [['Total', 'totalVerifications'], ['Approved', 'approvedCount'], ['Rejected', 'rejectedCount'], ['Review queue', 'queueDepth']],
            'cta' => ['label' => 'Open reports', 'var' => 'reportsUrl'],
            'required' => ['companyName', 'totalVerifications', 'approvedCount', 'rejectedCount', 'reviewCount', 'topReasons', 'queueDepth', 'webhookHealth'],
            'unsubscribe' => true,
        ],

        // Platform ops
        'ops_alert' => [
            'subject' => '[VerifyPass ops] {signal} on {hostId}',
            'preheader' => 'Operational signal requires attention.',
            'paragraphs' => [
                'Signal: {signal}. Host/worker: {hostId}. First seen {firstSeen} (UTC), last seen {lastSeen} (UTC).',
                '{detail}',
            ],
            'facts' => [['Signal', 'signal'], ['Host', 'hostId'], ['First seen', 'firstSeen'], ['Last seen', 'lastSeen']],
            'cta' => ['label' => 'Open runbook', 'var' => 'supportUrl'],
            'required' => ['signal', 'hostId', 'firstSeen', 'lastSeen', 'detail'],
        ],
    ];

    /** @return array<string,mixed> */
    public static function get(string $id): array
    {
        if (!isset(self::CATALOG[$id])) throw new \InvalidArgumentException("Unknown template: {$id}");
        return self::CATALOG[$id];
    }
}
