name: sample-app-demo-build
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  demo:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: demo
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - run: npm ci --prefix frontend/sdk/react
      - run: npm ci --prefix sample-app && npm run build --prefix sample-app
        env:
          VITE_VP_API_BASE: ${{ vars.DEMO_API_URL }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: restricted-demo-${{ github.sha }}
          path: sample-app/dist/
          retention-days: 7